export const AnalyticsActions = {
  PAGE_VIEW: "VIEW",
  BUTTON_CLICK: "CLICK",
  FORM_SUBMIT: "SUBMIT",
  CHAT_WIDGET_OPENED: "CHAT_WIDGET_OPENED",
  CHAT_WIDGET_CLOSED: "CHAT_WIDGET_CLOSED",
  ACCESS_FREE_CONTENT: "ACCESS_FREE_CONTENT",
  CHECKOUT_INTENT: "CHECKOUT_INTENT",
  CHECKOUT_COMPLETED: "CHECKOUT_COMPLETED",
};
